{
    'name': "Management",
    'summary': """Various functionalities in the context of management""",
    'author': "Mint System GmbH",
    'website': "https://www.mint_system.ch",
    'license': "AGPL-3",
    'category': 'Services/Management',
    'version': "16.0.0.0.1",
    'depends': ['base', 'mail'],    
    'data': [
        'views/mgmt.xml',
        'views/mgmt_audit.xml',
        'views/mgmt_requirement.xml',
        'views/mgmt_compliance.xml',
        'views/mgmt_document.xml',
        'views/mgmt_configuration.xml',
        'views/mgmt_nonconformity.xml',
        'views/mgmt_compliancematrix.xml',
        'views/mgmt_regulation_template.xml',  
        # 'views/mgmt_compliancestatement.xml',
        'security/mgmt_security.xml',
        'security/ir.model.access.csv', 
        'reports/audit_report.xml',
        'data/mgmt.audit.type.csv',
        'data/mgmt.audit.category.csv',        
        'demo/res.partner.csv',
        'demo/mgmt.document.csv',
        'demo/mgmt.audit.csv',
        'demo/mgmt.requirement.csv',
        'demo/mgmt.compliancestatement.csv',
    ], 
}